### ISSUE TITLE
JMiniZinc java code example

### ISSUE THREAD

**Issue by lgiannelli** [siemens/JMiniZinc#20]
Hi, I'm interested to use/have some example of a simple java code like "8 queens problem". Particullary I would undestand if is it possible to get the result of the model into java variables (I have to write those variables in a database).
thanks
Luca

**Comment by rtaupe** [comment]
Hi Luca,
I have added [NQueensDemo.java](https://github.com/siemens/JMiniZinc/blob/25b9fdc154dc6185f81ae3ede3feed6fe985515e/com.siemens.jminizinc.core/src/test/java/at/siemens/ct/jmz/NQueensDemo.java). Hope this illustrates how to achieve what you have described.
Unfortunately, using predicates is not yet supported by JMiniZinc, so you can´t use `alldifferent` (but you´re welcome to contribute if you want!).
-Richard

**Comment by lgiannelli** [comment]
Hi Richard,
thanks a lot for the code. It's great!
Luca
