### ISSUE TITLE
Parsing MiniZinc files for variables and their types

### ISSUE THREAD

**Issue by HelgeS** [siemens/JMiniZinc#3]
Hallo,

I would like to use JMiniZinc to parse a mzn file and extract the variables and their type declaration as a basis for further modeling. Is this currently possible with JMiniZinc? 

From the diag module I would assume yes, but I do not find the right starting point.

Thanks!

**Comment by rtaupe** [comment]
Hi,

thanks for your interest!
So far, JMiniZinc development has concentrated on the _generation_ of models, not their parsing. The classes in `at.siemens.ct.jmz.mznparser` provide just very basic functionality to be used by the diag module ...
A starting point would be to call `new MiniZincCP(File)`, but you will surely need to adapt and extend this so it can be used outside of the diag module.

Hope this helps.
