### ISSUE TITLE
Gradle translation

### ISSUE THREAD

**Issue by sdemarch** [siemens/JMiniZinc#31]
Hello,

I would like to build a project using your library with Gradle, since Maven and Gradle are likely to switch. I tried to add a dependency following the [pom.xml](https://github.com/siemens/JMiniZinc/blob/master/com.siemens.jminizinc/pom.xml) like this:
```
dependencies {
...
compile('com.siemens.jminizinc:core:1.5')
...
}
```
or, either
```
dependencies {
...
compile group: 'com.siemens.jminizinc', name: 'core', version: '1.5'
...
}
```
but Gradle refuses this configuration. 

Do you have some advice?
Thanks in advance

**Comment by rtaupe** [comment]
Hello,

probably you are the first one trying to do this with JMiniZinc.
Do I understand correctly that you have installed JMiniZinc to a local maven repository and you want to use it in another project that is built with Gradle?

What error message do you get?

Best,
Richard

**Comment by sdemarch** [comment]
Hi, and thanks for your answer.

Yes, you got exactly my problem; when I try to build my project I get this error:
```
Unknown host 'mvn.jasoft.fi'. You may need to adjust the proxy settings in Gradle.
```
which is quite weird as it doesn't refers directly to your API, but comes in when I include it.

**Comment by rtaupe** [comment]
Very weird. I´m not aware of any dependencies specific to `mvn.jasoft.fi`.

Also, I cannot reproduce the issue. An empty gradle project with [the build file attached](https://github.com/siemens/JMiniZinc/files/2961988/build.gradle.txt) (added file ending `.txt` to be able to upload) builds fine on my system.

**Comment by sdemarch** [comment]
Hi,

I managed to get it working, probably somehow the local repository was broken. I deleted and re-created it and now everything is fine.

Thanks for your help ;)
